spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create # DB ??? ?? (none, create, create-drop, update, validate - ?? ??? ??)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true     # ?? ?? ?? (??)
        show_sql: true       # ?? ?? ??

