spring:
  # DB 연결
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: rocket
    password: qwer123!
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # show_sql: true   # SQL 쿼리 콘솔 출력
        format_sql: true # SQL 쿼리 포맷팅

  # 스키마 초기화 설정
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html # UI 접속 경로
    operations-sorter: method # HTTP 메서드순 정렬
    tags-sorter: alpha # 컨트롤러명 알파벳순 정렬
  api-docs:
    path: /v3/api-docs # OpenAPI JSON 문서 경로

# JWT 설정 (보안을 위해 실제 배포 시 변경)
jwt:
  secret: d3e11a19fb2da11f7d2b5145934e462fb141f599fe7334739c59791c6fb30b77 # 64바이트 랜덤 문자열 (보안을 위해 실제 배포 시 변경)
  refresh_secret: a9c8b7d6e5f4g3h2i1j0k9l8m7n6o5p4q3r2s1t0u9v8w7x6y5z4a3b2c1d # 64바이트 랜덤 문자열 (보안을 위해 실제 배포 시 변경)
  expiration_time: 300 # 개발 시: 300분으로 설정
#  expiration_time: 30 # 액세스 토큰 만료 시간(분)

# 개발용 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug  # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 바인딩 값도 출력
    org.hibernate.query.sqm.function: info  # 함수 등록 로그 숨김
    org.hibernate.orm: info  # Hibernate 내부 설정 로그 줄임

fastapi:
  base-url: http://localhost:8000

kernel:
  gateway:
    url: http://localhost:8888
    token: rocket