spring:
  # DB 연결
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: rocket
    password: qwer123!
    driver-class-name: org.postgresql.Driver

  # schema.sql 실행
  sql:
    init:
      mode: never # 개발 초기 미실행
      schema-locations: classpath:db/schema.sql

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create # 개발 초기 실행
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # show_sql: true   # SQL 쿼리 콘솔 출력
        format_sql: true # SQL 쿼리 포맷팅

logging:
  level:
    org.hibernate: DEBUG # SQL 쿼리 로그 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 파라미터 값 출력