spring:
# spring:
#   websocket:
#     allowed-origins: https://your-frontend-domain.com
  # DB 연결
  datasource:
    url: jdbc:postgresql://postgres_container:5432/user_db
    username: rocket
    password: qwer123!
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # show_sql: true   # SQL 쿼리 콘솔 출력
        format_sql: true # SQL 쿼리 포맷팅
        jdbc:
          time_zone: Asia/Seoul # 한국 시간(Asia/Seoul) 기준으로 설정

  # 스키마 초기화 설정
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  # Redis 설정
  data:
    redis:
      host: webide-redis-1
      port: 6379

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html # UI 접속 경로
    operations-sorter: method # HTTP 메서드순 정렬
    tags-sorter: alpha # 컨트롤러명 알파벳순 정렬
  api-docs:
    path: /v3/api-docs # OpenAPI JSON 문서 경로

# JWT 설정 (보안을 위해 실제 배포 시 변경)
jwt:
  secret: {JWT_SECRET}
  refresh_secret: {JWT_REFRESH_SECRET}
  expiration_time: 30 # 액세스 토큰 만료 시간(분)

# 개발용 로깅 설정
logging:
  level:
    org.hibernate.SQL: info  # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql.BasicBinder: info  # 바인딩 값도 출력
    org.hibernate.query.sqm.function: info  # 함수 등록 로그 숨김
    org.hibernate.orm: info  # Hibernate 내부 설정 로그 줄임
    root: info

fastapi:
  base-url: http://fastapi-server:8000